version: "2"
services:

  indexer:
    build:
      context: .
      dockerfile: Dockerfile-indexer
    volumes:
      - ./data:/home/search/data
    ports:
      - "873:873"
    ulimits:
      as: 40802189312
      nofile: 51200
    restart: always
    environment:
      SEARCH_HOME: /home/search
      INDEXES_VERSION: 1
      POSTGRES_HOST: 10.0.2.15
      POSTGRES_PORT: 5432
      POSTGRES_DB: musicbrainz_db
      POSTGRES_USER: musicbrainz
      POSTGRES_PASSWD: musicbrainz

  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8080:8080"
    ulimits:
      as: 40802189312
      nofile: 51200
    restart: always
    environment:
      SEARCH_HOME: /home/search
      RSYNC_SERVER: indexer
      RSYNC_PASSWORD: search
      INDEXES_VERSION: 1
    depends_on:
      - indexer
